version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LOAD_INITIAL_DATA=true
    volumes:
      - ./data:/app/data
      - ./nutrition_test.db:/app/nutrition_test.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 